parameters:
#    immobilier_budget.example.class: Immobilier\BudgetBundle\Example

services:
#    immobilier_budget.example:
#        class: %immobilier_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
