parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: Immobilier_Lanos
    database_user: root
    database_password: bambihac
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 82de7c074fb50120c4d36d1391b773aa342f7f19
    database_path: null
