<?php

namespace Immobilier\BudgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BudgetGestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetGestRepository extends EntityRepository
{
}
